steps:
  - id: install
    name: node:19.1.0-alpine3.16
    dir: single-page-application
    entrypoint: npm
    args:
      - ci
  - id: eslint
    name: node:19.1.0-alpine3.16
    dir: single-page-application
    entrypoint: npm
    args:
      - run
      - lint
  - id: test
    name: node:19.1.0-alpine3.16
    dir: single-page-application
    entrypoint: npm
    env:
      - "CI=true"
    args:
      - run
      - test
  - id: cypress test
    name: node:19.1.0-alpine3.16
    dir: single-page-application
    entrypoint: npx
    args:
      - cypress
      - run
      - --component
  - id: build
    name: node:19.1.0-alpine3.16
    dir: single-page-application
    entrypoint: npm
    args:
      - run
      - build
