version: "3.9"
services:
  bff:
    container_name: bff
    build:
      context: .
      dockerfile: bff/Dockerfile
    ports:
      - "8080:8080"
    environment:
      TODO_SERVICE_HOST: "todo-service:8081"
      STAGE: "local"
  todo-service:
    container_name: todo-service
    build:
      context: .
      dockerfile: todo-service/Dockerfile
    environment:
      PORT: 8081
      MOCK_DATASTORE: "true"
